// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9kOAVEUAypYN10WcrzvN1p25JlPuQXo',
    appId: '1:666579397332:web:1cd5721bd918182dace941',
    messagingSenderId: '666579397332',
    projectId: 'policeinventory',
    authDomain: 'policeinventory.firebaseapp.com',
    storageBucket: 'policeinventory.appspot.com',
    measurementId: 'G-G6HBF5B3HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi98Z3mDm3iJZE0y5QFZmGVhcNHqJ8pWw',
    appId: '1:666579397332:android:4622ba1ac72cde68ace941',
    messagingSenderId: '666579397332',
    projectId: 'policeinventory',
    storageBucket: 'policeinventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYVc30G_FijKDpcXC_rR-0QWRdy3FPw8',
    appId: '1:666579397332:ios:88cb1697e9215ea0ace941',
    messagingSenderId: '666579397332',
    projectId: 'policeinventory',
    storageBucket: 'policeinventory.appspot.com',
    iosBundleId: 'com.example.policeinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYVc30G_FijKDpcXC_rR-0QWRdy3FPw8',
    appId: '1:666579397332:ios:88cb1697e9215ea0ace941',
    messagingSenderId: '666579397332',
    projectId: 'policeinventory',
    storageBucket: 'policeinventory.appspot.com',
    iosBundleId: 'com.example.policeinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT9kOAVEUAypYN10WcrzvN1p25JlPuQXo',
    appId: '1:666579397332:web:deeacd3eaf86be4eace941',
    messagingSenderId: '666579397332',
    projectId: 'policeinventory',
    authDomain: 'policeinventory.firebaseapp.com',
    storageBucket: 'policeinventory.appspot.com',
    measurementId: 'G-8C61Q82Y5B',
  );
}
